# Voice Status Icons
talking: "🔊"
whispering: "🔉"
quiet: "🔈"
deafened: "❌" # when the player is connected but e.g. muted
disconnected: "🛠" # when the player does not have the the mod installed
# Group Status Icons
normal_group: "👥N"
open_group: "👥O"
isolated_group: "👥I"
not_in_group: ""
# Config
talk_timeout_ms: 300 # Time in milliseconds after which the talking icon stops. 300 works well for most use cases.